### ISSUE TITLE
Error in Launch the lsd_slam viewer

### ISSUE THREAD

**Issue by Moha555** [tum-vision/lsd_slam#228] opened 2016-11-09 16:36 UTC
Hi!
 I use `roscore` in a terminal and `rosrun lsd_slam_viewer viewer` in another terminal.
But I receive below errors:
`
Started QApplication thread
libGL error: pci id for fd 16: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
Started ROS thread
[ INFO] [1478707931.856605266]: lsd_slam_viewer started
`
I follow the installation procedure as in the README and I'm beginner in Linux OS.
what might be wrong?

**Comment by af-silva** [comment] 2016-11-09 16:51
Hi,
Are you running the LSD-SLAM in a virtual machine???

**Comment by Moha555** [comment] 2016-11-09 17:09
Hi, 
yes

**Comment by af-silva** [comment] 2016-11-10 12:28
Hi, 

That is a hard problem to solved without seeing what is going on in the machine. Bu you can try to enable hardware acceleration in your Virtual Machine and make sure that you have the VirtualBox Extension Pack installed. If the problem persists try to look around  for the specific error that you are getting when trying to run the code  `libGL error: failed to load driver: vboxvideo` .

And I don't have experience running this code on a virtual machine, so I don't know how it behaves, but from my experience the LSD-SLAM uses a lot of resources from the machine and in a virtual environment can be a little slow... 

Sorry if I can't help you more than this :)

**Comment by romdos** [comment] 2016-11-15 06:31
I have the next error running lsd_slam_viewer
![lsdslamerror](https://cloud.githubusercontent.com/assets/15799418/20295492/4ca94b06-ab16-11e6-8d23-74c54c7db736.png)

**Comment by Moha555** [comment] 2016-11-15 11:17
Dear @af-silva 
My problem is solved... :)
Virtual machine could not run this code
I tried to run it on the Ubunto OS , and eventually it's ran.

**Comment by af-silva** [comment] 2016-11-17 17:10
@romdos I thinks it's better to you to create a Issue related to the problem that your project instance is invoking. Second please provide more information, because just with the error is very difficult to help (e.g. are you using rosbuild or catkin? ). You could try to delete the devel and build folders and compile everything again... it's a memory problem but I don't know what is causing it.

@Moha555 Nice :) happy hacking :p 
If the problem is solved please close the issue, to maintained the issue list clean.

**Comment by romdos** [comment] 2016-11-18 09:02
@af-silva, I have created new issue https://github.com/tum-vision/lsd_slam/issues/230

**Closed as completed** 2016-11-19 09:23 UTC
