### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by snakehaihai** [tum-vision/lsd_slam#14] opened 2014-09-23 08:10 UTC
hi
i followed the instruction 
Launch the lsd_slam viewer:

```
    rosrun lsd_slam_viewer viewer
```

Launch the lsd_slam main ros node:

```
    rosrun lsd_slam_core live_slam image:=/image_raw camera_info:=/camera_info
```

Play the sequence:

```
    rosbag play ~/LSD_room.bag
```

and have a segmentation fault error

Then i dig in the function to check out where is the error using print and find the error is at the frame.cpp

if (width % 8 == 0)
    {
        __m128 p025 = _mm_setr_ps(0.25f,0.25f,0.25f,0.25f);
        printf("__m128 p025 \n");
        const float\* maxY = source+width_height;
        for(const float_ y = source; y < maxY; y+=width_2)
        {
            const float_ maxX = y+width;
            printf("__m128 p025 y%f \n",&y);
            //if(maxX
            for(const float\* x=y; x < maxX; x += 8)
            {
                printf("__m128 p025 x%f %f\n",&x,&maxX);
                // i am calculating four dest pixels at a time.

```
            __m128 top_left = _mm_load_ps((float*)x);
            printf("_mm_load_ps");
            __m128 bot_left = _mm_load_ps((float*)x+width);
            __m128 left = _mm_add_ps(top_left,bot_left);
            printf("left");
            __m128 top_right = _mm_load_ps((float*)x+4);
            __m128 bot_right = _mm_load_ps((float*)x+width+4);
            __m128 right = _mm_add_ps(top_right,bot_right);
            printf("right");

            __m128 sumA = _mm_shuffle_ps(left,right, _MM_SHUFFLE(2,0,2,0));
            __m128 sumB = _mm_shuffle_ps(left,right, _MM_SHUFFLE(3,1,3,1));
            printf("sumB");

            __m128 sum = _mm_add_ps(sumA,sumB);
            sum = _mm_mul_ps(sum,p025);

            _mm_store_ps(dest, sum);
            printf("_mm_store_ps");
            dest += 4;
        }
    }

    data.imageValid[level] = true;
    return;
}
```

I add the print and the outcome is shown below

numData[level] > 0
pyrIdepthVarSource
buildImage 
__m128 p025 
__m128 p025 y0.000000 
__m128 p025 x-0.124992 -0.000000
Segmentation fault (core dumped)

previous are the print function from caller function. 
is there anyway to fix this error?

**Comment by snakehaihai** [comment] 2014-09-23 08:24
and of course I did the 
Install system dependencies:

```
sudo apt-get install ros-fuerte-libg2o liblapack-dev libblas-dev freeglut3-dev libqglviewer-qt4-dev
```

In your ROS package path, clone the repository:

```
git clone https://github.com/tum-vision/lsd_slam.git lsd_slam
```

Compile the two package by typing:

```
rosmake lsd_slam
```

**Comment by snakehaihai** [comment] 2014-09-23 08:33
quick update. 
I changed another computer with old 12.04 and fuerte. and now it is working

**Comment by JakobEngel** [comment] 2014-09-24 09:49
Hmm, not sure what may be the cause of the segfault. A quick fix would be to just remove the whole loop, such that the non-SSE version is used (-> slightly worse performance).
Can you tell me on which pyramid level the segfault occurs (what is width and level), and if it works on other pyramid levels or always crashes? Also, the debug output whiting the loop is missing "\n", and hence will not be flushed before the segfault.
otherwise I cannot do much, as I cannot reproduce the error ;)

**Comment by snakehaihai** [comment] 2014-09-24 10:37
thanks for the reply. but I did reformat my desktop pc , clone the working os to desktop pc and problem didn`t appear anymore. what i posed was what only source of the problem left.
 about what pyramid level, the debug message from each calling function only appear once. which means it is at first calling instance. it gives out the error. 
I was using 12.04.03 and grovvy, and was configured to use catkin and then configured to use rosmake
those reasons could cause the problems.

**Comment by MartinMeliss** [comment] 2014-09-25 17:10
Hello! 
Do I have a "Segmentation fault (core dumped)" on any available to me at the moment
configuration Ros + Ubuntu. But I'm working with ROS under a virtual machine (error occurs in vmware and virtualbox after several (5-7) frames of a video sequence).

After compiling debug version I get an extended error info: 
"dataset: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:78: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = double; int Size = 4; int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " ***\* READ THIS WEB PAGE !!! ****"' failed."

start with: rosrun lsd_slam_core dataset _files:=/home/martin/LSD_room/images _hz:=25 _calib:=/home/martin/LSD_room/cameraCalibration.cfg

extended error information was obtained in:
VmWare 9.0.1 build-894247
Ubuntu 14.04
ROS Indigo

**Comment by JakobEngel** [comment] 2014-09-28 11:06
Hmm, that looks familiar (see issue #3), there seems to be a SSE alignment bug with 32bit architectures - which unfortunately I cannot test, as I only have 64bit systems. Can you provide a stacktrace of where the error occurs? See the linked website for more info.

**Comment by MartinMeliss** [comment] 2014-09-29 10:26
I disabled the SSE. 
I will try to get stacktrace, though I'm not good at debugging under Linux.

**Comment by adwaitgandhe** [comment] 2014-10-08 21:13
I just ran into the same issue MartinMeliss mentioned. I am using 32-bit Ubuntu 14.04 with ROS Indigo. I will try to see if I can debug this further. For now I am going to go to a 64-bit version to get the application working.

**Comment by JakobEngel** [comment] 2014-10-09 12:18
@artivis kindly provided a version which works on 32bit systems, fixing all the Eigen aligned problems (thanks!). It still works the same on 64bit systems (at least for me). For now, I put it in a separate branch (32bit), and will merge it into master after I get some positive feedback that it doesn't break anything :)

**Comment by QichaoXu** [comment] 2014-10-22 13:34
hello,
I have also a segmentation fault (core dumped) error.I'm trying hard get it right. My system configurations is ROS fuerte + Ubuntu 12.04.
@JakobEngel，what you mean by "A quick fix would be to just remove the whole loop"，I mean, how?

**Comment by JakobEngel** [comment] 2014-10-22 14:36
it should be fixed in the 32bit branch - can you try that?

"Remove the whole loop" == "remove lines 520 to 553 from frame.cpp". Then it will default to the non-SSE code, which is slower, but should not segfault. However, that's obviously not a clean fix, and might just lead to some other error somewhere else ;)

**Closed as completed** 2014-10-31 09:40 UTC
