### ISSUE TITLE
How to evalute ORB-SLAM2 (and LSD-SLAM) on the TUM RGB-D Benchmark dataset? 

### ISSUE THREAD

**Issue by haidela** [tum-vision/lsd_slam#288] opened 2017-10-27 20:43 UTC
Good evening, How to evalute Absolute Trajectory Error(ATE) using KITTI dataset or EuRoC on Matlab?

**Comment by MichaelGrupp** [comment] 2017-10-30 11:45
Duplicate of https://github.com/raulmur/ORB_SLAM2/issues/454 - see my answer there...

**Comment by haidela** [comment] 2017-10-30 14:41
@MichaelGrupp, thank you very much, it works well, as I am a beginner and I am trying to make my own ground truth

**Comment by MichaelGrupp** [comment] 2017-10-30 15:27
ok, glad to help :+1:

**Closed as completed** 2017-11-03 03:51 UTC
